### ISSUE TITLE
[Feature request] 配置撤回为可选行为

### ISSUE THREAD

**Issue by SherkeyXD** [Refound-445/nonebot-plugin-nailongremove#1]
可以只提醒 这样非管理员bot也能用

**Comment by NoNormalCreeper** [comment]
如果你想临时设置为无需撤回，可以暂时修改 `nonebot_plugin_nailongremove/handler.py` 文件的[第 65 行](https://github.com/Refound-445/nonebot-plugin-nailongremove/blob/e001804c5dae8fd56a2a3912154503e7605fa43b/nonebot_plugin_nailongremove/handler.py#L65)：
```python
                    await bot.call_api('delete_msg', message_id=event.message_id)
````

将它注释掉，Bot 即会不撤回只提醒。
