### ISSUE TITLE
Can you add support for pdm?

### ISSUE THREAD

**Issue by afterow** [Refound-445/nonebot-plugin-nailongremove#18]
If you cannot install using pdm, can you refer to https://github.com/pdm-project/pdm/issues/694 to modify the project's [pyproject.toml](https://github.com/Refound-445/nonebot-plugin-nailongremove/blob/main/pyproject.toml)?Thank you for looking at this issue, I hope it doesn't bother you.

**Comment by lgc2333** [comment]
i don't have any problem with install packages using pdm, and i can run this project without gpu without any issue. if you have, please open a pr by yourself.

**Comment by afterow** [comment]
OK, I will submit a PR on 星期八 when I have time.
