### ISSUE TITLE
一个问题

### ISSUE THREAD

**Issue by Dawnighting** [Refound-445/nonebot-plugin-nailongremove#19]
![910223de0192ffb0dff123cdcee3a87f](https://github.com/user-attachments/assets/40d69c78-7076-4320-ae87-5be2db078b52)
![1379e0b537a6d8e9b8f709345a2dbd17](https://github.com/user-attachments/assets/d05d8cbd-03cd-47a6-a8cc-e6a3b085d6fc)
运行时初始化的网址怎么404了，这样的话需要手动下载模型然后导入吗？我是小白不太懂，求大佬解答

**Comment by lgc2333** [comment]
更新插件

**Comment by Refound-445** [comment]
不要用镜像源

**Comment by Dawnighting** [comment]
> 不要用镜像源
是的，没用镜像源这次能运行了，已经能跑了，谢谢
