### ISSUE TITLE
后台报keyError错误

### ISSUE THREAD

**Issue by billyosoror** [Refound-445/nonebot-plugin-nailongremove#2]
bot为管理员状态
![QQ截图20241021165341](https://github.com/user-attachments/assets/f2cb8d3a-9ea6-4050-b491-3b33f2ccd08c)

**Comment by Refound-445** [comment]
> bot为管理员状态 ![QQ截图20241021165341](https://private-user-images.githubusercontent.com/53106983/378346082-f2cb8d3a-9ea6-4050-b491-3b33f2ccd08c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1MDU4NjIsIm5iZiI6MTcyOTUwNTU2MiwicGF0aCI6Ii81MzEwNjk4My8zNzgzNDYwODItZjJjYjhkM2EtOWVhNi00MDUwLWI0OTEtM2IzM2YyY2NkMDhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIxVDEwMTI0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhZTc5ZGEyZDFiZTE3NmM2ZDZiOWI5N2E3MWE1ZDRkYzgzYjE5NTZkYmRkNGQxOTUxMjAzYzdlZDIwZDljOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1y7pAVcRdqtRJyQw0NDvMdPhdCfptPHyfCD0f67MmUs)

检查一下适配器，目前仅支持"OneBot V11"

**Comment by Refound-445** [comment]
检查一下适配器，目前仅支持"OneBot V11"
