### ISSUE TITLE
模型识别问题？

### ISSUE THREAD

**Issue by YuYue-Amatsuki** [Refound-445/nonebot-plugin-nailongremove#20]
如下图，会将不是奶龙的表情包识别成奶龙
![IMG20241105124828.jpg](https://github.com/user-attachments/assets/6028f382-8680-4a10-91c4-77ea7ac4d5b2)

表情包样例如下
![Image_1730782128731.gif](https://github.com/user-attachments/assets/6e18d643-f150-4c0b-b97d-de385d920e3a)

![Image_1730782121422.gif](https://github.com/user-attachments/assets/4b8fc117-425d-4e7d-acff-d19052a60fbf)

![Image_1730782118351.gif](https://github.com/user-attachments/assets/d5d53a90-30d9-4f23-b2c6-2bbf7615f5d1)

**Comment by YuYue-Amatsuki** [comment]
补充
![Image_1730782316195.jpg](https://github.com/user-attachments/assets/ab0de39a-505a-4cbb-8811-20bf2bd26101)

![Image_1730782332306.gif](https://github.com/user-attachments/assets/dff354f9-3e4e-4210-990f-55baf9d808a3)

**Comment by lgc2333** [comment]
related to #6

建议加文档中的群聊反馈

**Comment by Refound-445** [comment]
v2.3.3 更新支持 -> 临时报错解决方案
