### ISSUE TITLE
新模型

### ISSUE THREAD

**Issue by Hakureirm** [Refound-445/nonebot-plugin-nailongremove#21]
https://huggingface.co/spaces/Hakureirm/NailongKiller
https://huggingface.co/spaces/Hakureirm/NailongKiller-CPU
用~~yolo11n和万张奶龙数据集训练~~（**24-11-16，数据集添加了许多种类上千张黄色物体重新训练**）了一个效果不错的模型，十分轻量，可以试试，有提供模型和HF的API，还有来源的数据集。
现已改为yolo11x模型，数据集添加了许多种类上千张黄色物体重新训练
#20 提到的这些图片全都不会错误识别。准确率很高
可以直接调用api跑，用的ZeroGPU，一张差不多8ms
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/334c44e0-777f-4357-82c2-9d121a458bd1">
也可以直接部署，速度的话，2核的小鸡半秒内就能算完。
上GPU就是个位数ms了。
yolo11的环境十分容易部署，分分钟搞定

**Comment by Hakureirm** [comment]
有自己尝试改这个插件，但是实在不熟悉，改了一下午还没成功，只能作罢了

**Comment by mc5024** [comment]
识别不了gif吗，看起来截取的图片是黑白的

**Comment by Hakureirm** [comment]
> 识别不了gif吗，看起来截取的图片是黑白的
QQ表情包后缀改为jpg，会抽取第一帧来计算
https://github.com/user-attachments/assets/2f813282-c28e-4787-8104-fb440ff6fa3d

**Comment by mc5024** [comment]
> > 识别不了gif吗，看起来截取的图片是黑白的
> 
> QQ表情包后缀改为jpg，会抽取第一帧来计算
> 
>  2024-11-16.14.41.39.mov

好的感谢

**Comment by mc5024** [comment]
![image](https://github.com/user-attachments/assets/9be0dc11-34ee-4b2d-9d30-f18cc051cc12)
<img width="1028" alt="屏幕截图 2024-11-16 162358" src="https://github.com/user-attachments/assets/7c6b42b9-f09e-43a6-8a54-2291d028b15e">
率先找出一张失败图片

**Comment by Hakureirm** [comment]
> ![image](https://private-user-images.githubusercontent.com/79186657/386831701-9be0dc11-34ee-4b2d-9d30-f18cc051cc12.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4MjA2NDgsIm5iZiI6MTczMTgyMDM0OCwicGF0aCI6Ii83OTE4NjY1Ny8zODY4MzE3MDEtOWJlMGRjMTEtMzRlZS00YjJkLTlkMzAtZjE4Y2MwNTFjYzEyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE3VDA1MTIyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyZWE4OTU3M2Y2MjQzNGU5NzY1OTE4OTk5NDljZjlhZjc1NWNhYmNkNDkyMjI4YjE1NmMxODk4ZTBjMjkyZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.r8ksgDbQnl59_98UGGpzl526vLMzgyUdpA3iYcLwVW4) <img alt="屏幕截图 2024-11-16 162358" width="1028" src="https://private-user-images.githubusercontent.com/79186657/386831715-7c6b42b9-f09e-43a6-8a54-2291d028b15e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4MjA2NDgsIm5iZiI6MTczMTgyMDM0OCwicGF0aCI6Ii83OTE4NjY1Ny8zODY4MzE3MTUtN2M2YjQyYjktZjA5ZS00M2E2LThhNTQtMjI5MWQwMjhiMTVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE3VDA1MTIyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjMTY1ZTliMTM1ZGViZGU4YzQ4MzVlMmM0Y2ViNTE0OWIxY2JiNTIwYjM1YTlkMmU5MGViNjMwYzM1M2FjNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5kftrhSZ9qUZmcHGwGNa4L8m5Oe8TMItrT4TqlDsb0Y"> 率先找出一张失败图片

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/6e742d60-8678-47b4-a9b9-ba8a467a46b9">

现在应该可以了

**Comment by TU-O0T** [comment]
![Image_1732012153871](https://github.com/user-attachments/assets/4f7f227e-5343-4ef5-856b-af42bf73e673)
再次发现漏网之鱼

**Comment by Hakureirm** [comment]
![image](https://github.com/user-attachments/assets/d4b3196c-df9b-45d1-899e-770a6441dccb)

没问题呀，bot插件可以选择遍历动图每一帧。hf spaces里边的只识别第一帧

**Comment by Hakureirm** [comment]
> ![Image_1732012153871](https://github.com/user-attachments/assets/4f7f227e-5343-4ef5-856b-af42bf73e673)
> 
> 再次发现漏网之鱼

![image](https://github.com/user-attachments/assets/d4b3196c-df9b-45d1-899e-770a6441dccb)

没问题呀，bot插件可以选择遍历动图每一帧。hf spaces里边的只识别第一帧

**Comment by Hakureirm** [comment]
> ![image](https://github.com/user-attachments/assets/9be0dc11-34ee-4b2d-9d30-f18cc051cc12)
> 
> <img width="1028" alt="屏幕截图 2024-11-16 162358" src="https://github.com/user-attachments/assets/7c6b42b9-f09e-43a6-8a54-2291d028b15e">
> 
> 率先找出一张失败图片

![image](https://github.com/user-attachments/assets/6765eba8-4200-4e54-88e2-dce513ca120f)

插件部署的没问题

**Comment by mc5024** [comment]
![Uploading S41120-14133331_com.android.chrome.png…]()
