### ISSUE TITLE
[求助] 无法使用插件

### ISSUE THREAD

**Issue by FlipWind** [Refound-445/nonebot-plugin-nailongremove#22]
rt.

使用 Napcat Docker。
服务器是 Linux Ubuntu 22.04。
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
![image](https://github.com/user-attachments/assets/68a9056d-a714-4f49-8c06-765d164333c8)

太菜了，求大佬看看。/bx

**Comment by Refound-445** [comment]
opencv没装好
https://blog.csdn.net/qq_50195602/article/details/124188467

**Comment by FlipWind** [comment]
> opencv没装好 https://blog.csdn.net/qq_50195602/article/details/124188467


有用，谢谢！
但是我的服务器配置太低貌似跑不起来((
