### ISSUE TITLE
求助：能识别消息但是无法撤回

### ISSUE THREAD

**Issue by caber1345** [Refound-445/nonebot-plugin-nailongremove#23]
这是打开#启动后出现的
![1a13decab410247e6a073f4b4c8962fd](https://github.com/user-attachments/assets/c25d6389-6bc5-45c4-9510-29bf1d207228) 
这是安装时报错的
![1668da0723a073225e628635e6304970](https://github.com/user-attachments/assets/7cbfccb3-2f09-4049-919d-c9207f40257f)
用的anaconda，感谢各位

**Comment by Refound-445** [comment]
没装环境依赖，建议重装一次，在nb bs时，如果已存在虚拟环境可以不用再次创建，但是选择安装依赖的时候要选Yes

**Comment by caber1345** [comment]
> 没装环境依赖，建议重装一次，在nb bs时，如果已存在虚拟环境可以不用再次创建，但是选择安装依赖的时候要选Yes

重装一遍之后搞定了，感谢
