### ISSUE TITLE
QQ官方机器人发出来的奶龙图片似乎无法触发规则

### ISSUE THREAD

**Issue by extrant** [Refound-445/nonebot-plugin-nailongremove#26]
11-22 11:20:21 [SUCCESS] nonebot | OneBot V11 25745***** | [message.group.normal]: Message -351904150 from 38890*****@[群:7087*****] '[at:qq=26871*****,name=@"十三州府"通过扫描二维码加入群聊] \n图库来源系用户投喂 如有侵权加群9244*****反馈删除'

解析的结果里没有[image:file=]

**Comment by Refound-445** [comment]
看起来是依赖问题，nonebot暂时无法处理md消息，等待依赖更新适配
