### ISSUE TITLE
是否支持撤回后不发送消息提醒

### ISSUE THREAD

**Issue by mwx2006** [Refound-445/nonebot-plugin-nailongremove#28]
如题，这么做可以在一定程度上减少打扰

**Comment by cyontingale** [comment]
在config里把提醒那句话删掉就可以了）

**Comment by mwx2006** [comment]
> 在config里把提醒那句话删掉就可以了）
> 

如果不配置此项会使用默认值，如果改为空字典程序无法正常启动，消息设置为空字符串会发出一条“该消息类型暂不支持查看”，消息字段改为None确实可以达到效果，但原理是引发异常中断处理，并不优雅

**Comment by Refound-445** [comment]
v2.3.3 已支持
