### ISSUE TITLE
处理图片时报错

### ISSUE THREAD

**Issue by Penixv** [Refound-445/nonebot-plugin-nailongremove#31]
![3e08a47bbd5e22e91a1bff1c0ce3b57b](https://github.com/user-attachments/assets/320c1bb9-2e5a-4201-b215-46d117ae91fc)
图片未撤回
配置文件如下
![image](https://github.com/user-attachments/assets/68803336-005c-4cea-bca8-290dabd5d930)

Python 3.12.7
插件和Nonebot均为最新

**Comment by chaos0713** [comment]
遇到了同样的问题，求解答
![QQ截图20241130012051](https://github.com/user-attachments/assets/59ee0827-5cb1-45ef-9d0c-6031bc8ce321)

**Comment by Refound-445** [comment]
科学上网，换代理

**Comment by Refound-445** [comment]
把httpx版本降到了0.27.2试试

**Comment by Penixv** [comment]
降级后已解决
