### ISSUE TITLE
是否意外commit了开发环境代码

### ISSUE THREAD

**Issue by Tanxunze** [Refound-445/nonebot-plugin-nailongremove#4]
昨天测试的时候发现所有图片都会被撤回，查看提交历史发现了handler.py中:
![image](https://github.com/user-attachments/assets/af854239-7421-467c-94c9-3104ce4dcb40)
正常逻辑应该使用model.py中的check_image函数吧，手动修改以后就运行正常了。

**Comment by Refound-445** [comment]
应该是之前调试忘记删了...
