### ISSUE TITLE
模型精度不够，把藤田琴音识别成奶龙了

### ISSUE THREAD

**Issue by EvolvedGhost** [Refound-445/nonebot-plugin-nailongremove#6]
藤田琴音怎么你了👿👿👿👿

sample：
![6d5765b6bd48d52cf64962c99e423f44](https://github.com/user-attachments/assets/96f329c3-17c4-4a70-bcf1-f20f4d3bea8b)
![0351b8e289cf454083c87d650492a2ca](https://github.com/user-attachments/assets/12f9e15c-1656-48af-9298-7f3d4feeb94a)

result：
![image](https://github.com/user-attachments/assets/4c4ab865-7718-42fa-9e3b-74bba202f4b4)
![image](https://github.com/user-attachments/assets/f8888762-8bdc-488d-b505-dac189912780)

**Comment by EvolvedGhost** [comment]
目前模型识别的更多是黄色的特征而不是奶龙的特征，黄色的表情包大概率误报，sample：
![0a95724188f3c00966049838f56715a1](https://github.com/user-attachments/assets/b7dca744-9a73-4e68-aff0-efa1bb180611)
![be5f2fa9c6b0372de60141f1d1bdd6f3](https://github.com/user-attachments/assets/74aab554-72fe-430e-8081-857ba858a1aa)
![ceb592ec42cc66542f9ce86c1eb1baa0](https://github.com/user-attachments/assets/59866c02-d140-461e-aedb-d6b978d19e56)
![7a342cc6dc391c8cae6102a89280b6b8](https://github.com/user-attachments/assets/7b729bc3-ca1d-4d7f-90de-c1eb8ad8bec3)

**Comment by EvolvedGhost** [comment]
![image](https://github.com/user-attachments/assets/6792ed0f-a8b9-47c8-a988-82c214cf08ff)

已使用25号下午4点的新模型，依然会误报

最极端的情况是，这个图也会认为是奶龙：
![1bdb38a77affe426d2962308ad99a8db](https://github.com/user-attachments/assets/08de6d4b-f1cd-4d93-bf45-22e21a653ba5)

**Comment by Refound-445** [comment]
# 这都被你发现了，我要把你也划入奶龙势力范围👿

**Comment by MultiWolf** [comment]
# 杀疯了😨
![图片](https://github.com/user-attachments/assets/d08e95ae-daca-4e19-b17d-56cb1b106cee)

**Comment by MultiWolf** [comment]
![图片](https://github.com/user-attachments/assets/4dd47266-1992-4caf-a852-2364e5233568)

**Comment by Refound-445** [comment]
在优化了，别骂了😭

**Comment by padoru233** [comment]
+1 误报率太高了不得不关掉

**Comment by SherkeyXD** [comment]
感觉是训练集当中黄色的反例不够多？

以及为啥是 11 分类，有啥渊源吗（

**Comment by SherkeyXD** [comment]
感觉是训练集当中黄色的反例不够多？

**Comment by kagg886** [comment]
# 我是奶龙

**Comment by kanocyann** [comment]
敢把我的琴音识别成奶龙？我要风风光光你

**Comment by RTAkland** [comment]
甚至可以吧这张照片识别成奶龙![image](https://github.com/user-attachments/assets/a1caea39-d4a9-4050-9c3a-fb414eaddedc)

**Comment by xian23346** [comment]
喜欢发藤田琴音的小朋友们你们好，我是奶龙😃

**Comment by synodriver** [comment]
**If it looks like a duck, walks like a duck and quacks like a duck, it's a duck.**

**Comment by cyontingale** [comment]
虹夏也成奶龙了，似乎黄毛都会识别成奶龙

**Comment by szdytom** [comment]
![6B50745874EFA1EAE2881079B73D6DCB](https://github.com/user-attachments/assets/92a45d97-96be-4c5d-8875-856fa280ce99)

**Comment by Refound-445** [comment]
插件和模型已更新，请安装最新版本使用，新的精度问题大乱斗请开new issue，欢迎大家继续反馈~
