### ISSUE TITLE
是否考虑支持 LLOneBot 以及 LiteLoaderQQNT？

### ISSUE THREAD

**Issue by SuoHouDaiShi** [Refound-445/nonebot-plugin-nailongremove#9]
如题
如果可以做的话，还麻烦做一下吧（

**Comment by lgc2333** [comment]
按理来说不应该不适配，请提供错误日志

**Comment by SuoHouDaiShi** [comment]
> 按理来说不应该不适配，请提供错误日志

我等服务器修好了试试吧，如果有结果我回复您（

**Comment by SuoHouDaiShi** [comment]
emmm 是这样，我服务器修好之后我查看了一下 LiteLoaderQQNT 的插件商店，其中并没有提供 NoneBot 协议支持的插件，LLOneBot 这个插件本身也并不支持 NoneBot，我本人也是个小白，如果能做的话还劳烦做一下吧，谢谢了（

**Comment by lgc2333** [comment]
你在说什么胡话
